### ISSUE TITLE
Ubuntu 14.04-x86 安装过程中,在let's encrypt成功获取证书后卡住

### ISSUE THREAD

**Issue by ghost** [aploium/zmirror-onekey#1]
IMPORTANT NOTES:
- Congratulations! Your certificate and chain have been saved at
  /etc/letsencrypt/live/google.zywz.ml/fullchain.pem. Your cert will
  expire on 2016-11-25. To obtain a new or tweaked version of this
  certificate in the future, simply run certbot-auto again. To
  non-interactively renew _all_ of your certificates, run
  "certbot-auto renew"
- If you lose your account credentials, you can recover through
  e-mails sent to zengyuan8@gmail.com.
- Your account credentials have been saved in your Certbot
  configuration directory at /etc/letsencrypt. You should make a
  secure backup of this folder now. This configuration directory will
  also contain certificates and private keys obtained by Certbot so
  making regular backups of this folder is ideal.
- If you like Certbot, please consider supporting our work by:
  
  Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
  Donating to EFF:                    https://eff.org/donate-le

安装到这里就不动了，系统是ubuntu-14.04-x86。

**Comment by aploium** [comment]
非常感谢!
出现这个问题的原因是在ubuntu14.04下, 命令 `service apache2 start` 与 tee 冲突
(tee用来重定向stdout的输出, 在脚本里用于收集debug信息)
两者一起使用的话, tee会出现无法结束的bug
已经修复(在使用那个命令的地方不使用tee)
在测试机器上安装通过

如果可能的话, 请重装系统后再进行一次安装
如果比较麻烦, 也可以按照以下命令删除之前下载的东西, 然后再来一遍

``` bash
rm deploy.py
rm -rf /etc/letsencrypt
rm -rf /var/www/*
rm /etc/apache2/sites-enabled/zmirror-*
```

**Comment by aploium** [comment]
收到成功部署报告, Bug已解决
