### ISSUE TITLE
youtube提示 验证码无效或已超时，请重试。

### ISSUE THREAD

**Issue by godzlalala** [aploium/zmirror-onekey#11]
配置完毕后其他网站没有问题，但是youtube报错

> 验证码无效或已超时，请重试。
> 
> 很抱歉打扰您。我们收到了大量来自您网络的请求。
> 要继续您的 YouTube 体验，请填写下面的表单。
> 
> 与网站所有者有关的错误：
> Invalid domain for site key

这个是因为我服务器的原因吗

**Comment by aploium** [comment]
应该是的, 但是具体我也不确定

**Comment by ghost** [comment]
应该是ip进入黑名单了
