### ISSUE TITLE
一键脚本安装速度很慢?

### ISSUE THREAD

**Issue by ghost** [aploium/zmirror-onekey#13]
为什么一键脚本安装很慢?几乎要半天的时间!!!

**Comment by aploium** [comment]
如果你是在国内机器, 不开国外代理的话, apt-get可能是非常缓慢的.  
可以使用国内的apt-get源来提高速度, 比如中科大的源, 具体请google

标准情况下(国外VPS)的安装是非常迅速的, 可以看readme中的演示视频
