### ISSUE TITLE
请问如何卸载一键部署的zmirror？

### ISSUE THREAD

**Issue by BoboCharlton** [aploium/zmirror-onekey#17]
RT
thanks！

**Comment by aploium** [comment]
1. 移除文件，直接进行rm的删除即可
   - `/var/www/` 下的镜像文件夹，名字很好认的
   - `/etc/apache2/sites-enabled/` 下的配置文件, 名字同样很好认
2. (可选) 移除Apache
   `sudo apt-get remove apache2`
3. (可选) 移除letsencrypt
   直接删除`/etc/certbot`与`/etc/letsencrypt`文件夹即可
