### ISSUE TITLE
zmirror bash script for ubuntu and CentOS6 x86_64

### ISSUE THREAD

**Issue by yumin9822** [aploium/zmirror-onekey#18]
闲来无事，搞了两个bash脚本。ubuntu debian, centos6。 Centos6 只支持x86_64。
脚本中有简单介绍！
https://github.com/yumin9822/zmirror-docker/blob/master/zmirror-debian.sh
https://github.com/yumin9822/zmirror-docker/blob/master/zmirror-ubuntu.sh
https://github.com/yumin9822/zmirror-docker/blob/master/zmirror-centos6.sh

**Comment by aploium** [comment]
非常感谢！

**Comment by seramat** [comment]
使用@yumin9822一键部署的，怎么限制request 2.11版本？
