### ISSUE TITLE
zmirror-onekey可不可以弄要输入密码才可以使用这个镜像？

### ISSUE THREAD

**Issue by ghost** [aploium/zmirror-onekey#2]

**Comment by aploium** [comment]
会的，不久后就会加入。

**Comment by aploium** [comment]
发现在bash(ubuntu 14.04)下, 无法输入中文
如果需要加输入密码的话, 就只能是英文提示语和英文密码答案了
不过也可以在脚本里设置成英文, 之后自己手动修改配置文件成中文

**Comment by aploium** [comment]
已经完成. (不过比较简陋)
在脚本的设置中只提供最基础的单一问题-答案验证, 如果需要更加丰富的验证方式, 
请看 `config_default.py` 文件中的 `Human/IP verification` 设置区段

在Ubuntu 14.04和Ubuntu16.04下测试通过
