### ISSUE TITLE
请问zmirror-onekey怎么没有移动版的youtube？

### ISSUE THREAD

**Issue by ghost** [aploium/zmirror-onekey#3]
刚在手机上打开PC版Youtube的镜像，它会显示移动版的界面，但是还显示“收到的响应无效。“。

**Comment by aploium** [comment]
那个youtube镜像是PC Only的，手机版现在还不能一键

**Comment by ghost** [comment]
那以后会加入吗？

**Comment by aploium** [comment]
移动版Youtube已经可以一键部署(于Ubuntu 14.04 x86 和 Ubuntu 16.04 x86_64 测试通过)
aploium/zmirror-onekey@b7ab84d7c7e98697deb722af17ad8ba079a87839
aploium/zmirror-onekey@599cc1387ac3117490e6bd9d4c49b848991a09e8
对应的, zmirror也把YoutubeMobile和PC分成了两个配置文件(本来不想分开的...因为差别只有两行)
aploium/zmirror@c684857cc82bf2698a04989259e189e60d8aa35f
