### ISSUE TITLE
报告，zimirror-onekey安装失败！

### ISSUE THREAD

**Issue by ghost** [aploium/zmirror-onekey#5]
我已经试过很多次了，都不能安装。另外我有个问题，以前我在一台VPS上成功安装过，现在又在另一台VPS上安装，而且设置的域名和邮箱也和上一个VPS的一样，这样会不会有问题？

[14:09:44] [WARNING] cert file for google.yandere.cf does not exist!
[14:09:44] [WARNING] unable to obtaining cert for google.yandere.cf
[14:09:44] [ERROR] 
I'm really sorry that we are not able to obtain an cert now, 
    This problem is NOT caused by zmirror-onekey itself, but caused by your DNS setting or the let's encrypt server. 
    If you had already set your A record correctly, please retry and wait, because sometimes the let's encrypt server may takes minutes or even hours to recognize your DNS settings.
    If you doesn't sure whether your DNS A record are correct, please check it using https://www.whatsmydns.net/
    Meanwhile, you can obtain cert manually using:        cd /etc/certbot && ./certbot-auto certonly -n --agree-tos -t -m "zengyuan8@gmail.com" --standalone -d "google.yandere.cf" 
[14:09:44] [INFO] For more information, please see http://tinyurl.com/zmcert
max retries exceed, do you want to continue retry?(Y/n)

**Comment by aploium** [comment]
理论上是不会有问题的
这一步的问题是letsencrtpt导致的，zmirror-onekey对此无能为力，如果长时间尝试无效
只能换一个域名

(我也不知道为什么letsencrypt不给你的域名发证书，dns记录应该是正确的)
