### ISSUE TITLE
executing python3 -m pip install -U distro error

### ISSUE THREAD

**Issue by BoboCharlton** [aploium/zmirror-onekey#6]
while executing python3 -m pip install -U distro, I got messages:
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

so I executed python3 -m pip install -U setuptools, and it worked well.
Is that a problem?

Environment:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Comment by aploium** [comment]
Thank you, and I have added the installation of setuptools in script.

btw, are you Chinese? I thought only Chinese can be interested in this project.

**Comment by BoboCharlton** [comment]
yes. i am 中国人...
