### ISSUE TITLE
一键部署工具部署谷歌完成后可以再次使用这个工具部署其他吗?

### ISSUE THREAD

**Issue by hnuzhoulin** [aploium/zmirror-onekey#7]
最开始是试一试，只部署了谷歌

现在想加别的站点，还是可以用这个一键部署工具吗？

**Comment by aploium** [comment]
是的，再次运行时会自动检测已经安装的镜像并忽略。
可以直接运行它来安装新的镜像，只是不带卸载功能:smile:
