### ISSUE TITLE
suggestion of adding a conf to disable ip direct access

### ISSUE THREAD

**Issue by yumin9822** [aploium/zmirror-onekey#9]
Here is a apache2 conf to disable ip direct access.
# no-ip-access.conf  http://paste.ubuntu.com/23357034/

`<VirtualHost *:443>`
`servername <IP_address>`
`documentroot /var/www/nosite/`
`</VirtualHost>`
`<VirtualHost *:80>`
`servername <IP_address>`
`documentroot /var/www/nosite/`
`</VirtualHost>`
# 

`mkdir -p /var/www/nosite`
`touch /var/www/nosite/index.html`
`echo "IP direct access is forbidden, Please use domain to access!" > /var/www/nosite/index.html`

**Comment by aploium** [comment]
Thank you very much.
However, server's IP may be difficult to determine, and may also change.

More important, in some cases, users will directly use (or change to) an IP as `my_host_name`

So, I don't want to ban direct IP access in the apache level. Instead, this feature will be added to zmirror itself. Any access whose domain doesn't equal to the `my_host_name`,  would be denied.

**Comment by yumin9822** [comment]
I made a simple docker images based on your zmirror-onekey.
https://hub.docker.com/r/yumin9822/zmirror/
https://github.com/yumin9822/zmirror-docker
